---
- name: Install NVIDIA GPU Exporter as a System Service
  hosts: nvidia_gpu
  become: yes
  vars:
    version: "1.4.1" # Актуальная версия
  tasks:
    - name: Download nvidia_gpu_exporter binary
      get_url:
        url: "https://github.com/utkuozdemir/nvidia_gpu_exporter/releases/download/v1.4.1/nvidia_gpu_exporter_1.4.1_linux_x86_64.tar.gz"
        dest: "/tmp/nvidia_gpu_exporter.tar.gz"

    - name: Unpack binary
      unarchive:
        src: "/tmp/nvidia_gpu_exporter.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Move binary to /usr/bin
      copy:
        src: "/tmp/nvidia_gpu_exporter"
        dest: "/usr/bin/nvidia_gpu_exporter"
        mode: '0755'
        remote_src: yes

    - name: Create system user for exporter
      user:
        name: nvidia_gpu_exporter
        system: yes
        create_home: no
        shell: /usr/sbin/nologin

    - name: Create Systemd service unit
      copy:
        dest: /etc/systemd/system/nvidia_gpu_exporter.service
        content: |
          [Unit]
          Description=Nvidia GPU Exporter
          After=network-online.target

          [Service]
          Type=simple
          User=nvidia_gpu_exporter
          Group=nvidia_gpu_exporter
          ExecStart=/usr/bin/nvidia_gpu_exporter
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable GPU Exporter service
      systemd:
        name: nvidia_gpu_exporter
        state: started
        enabled: yes
        daemon_reload: yes
