---
- name: Генерация секретных конфигов из Vault
  hosts: localhost
  connection: local
  vars_files:
    - vault.yml
  tasks:
    - name: Создание zfs-iscsi-secrets.yaml из шаблона
      template:
        src: templates/zfs-iscsi-secrets.j2
        dest: "../zfs-iscsi-secrets.yaml"
        mode: '0600' # Права только для владельца!
